#
# Format:
# 
# <stage name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   tag: <git tag pattern, optional>
#   repo: <git repository, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: davinl-circleci
  stack: cedar
  tag: production/*
  config:
    BUNDLE_WITHOUT: "development:test"

review:
  stack: cedar
  app:  davinl-circleci-review
  config: &default
    BUNDLE_WITHOUT: "development:test"

development: 
  app: davinl-circleci-test
  config: *default
